/*
dynamics_solver_forcespro_drl : A fast customized optimization solver.

Copyright (C) 2013-2025 EMBOTECH AG [info@embotech.com]. All rights reserved.


This software is intended for simulation and testing purposes only. 
Use of this software for any commercial purpose is prohibited.

This program is distributed in the hope that it will be useful.
EMBOTECH makes NO WARRANTIES with respect to the use of the software 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
PARTICULAR PURPOSE. 

EMBOTECH shall not have any liability for any damage arising from the use
of the software.

This Agreement shall exclusively be governed by and interpreted in 
accordance with the laws of Switzerland, excluding its principles
of conflict of laws. The Courts of Zurich-City shall have exclusive 
jurisdiction in case of any dispute.

*/

/* Generated by FORCESPRO v6.4.0 on Monday, October 13, 2025 at 1:49:19 PM */
#ifndef dynamics_solver_forcespro_drl_MEMORY_H
#define dynamics_solver_forcespro_drl_MEMORY_H

#include "dynamics_solver_forcespro_drl.h"


/* MEMORY STRUCT --------------------------------------------------------*/

#ifdef __cplusplus
extern "C" {
#endif
extern dynamics_solver_forcespro_drl_mem * dynamics_solver_forcespro_drl_internal_mem(solver_int32_unsigned i_mem);
#ifdef __cplusplus
}
#endif
#endif /* MEMORY_H */
