/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) dynamics_solver_forcespro_model_ ## ID
#endif

#include <math.h> 
#include "dynamics_solver_forcespro_model.h"

#ifndef casadi_real
#define casadi_real dynamics_solver_forcespro_float
#endif

#ifndef casadi_int
#define casadi_int solver_int32_default
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#if 0
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s3[21] = {1, 12, 0, 1, 2, 3, 4, 5, 5, 5, 5, 5, 5, 5, 6, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s4[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s5[20] = {2, 12, 0, 0, 0, 0, 2, 4, 4, 4, 4, 4, 4, 4, 5, 0, 1, 0, 1, 0};
static const casadi_int casadi_s6[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s7[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s8[15] = {3, 9, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 0, 1, 2};
static const casadi_int casadi_s9[32] = {9, 9, 0, 3, 6, 7, 12, 16, 20, 20, 20, 20, 2, 3, 4, 2, 3, 4, 5, 3, 4, 5, 6, 7, 3, 4, 5, 7, 3, 4, 5, 7};

/* dynamics_solver_forcespro_objective_0:(i0[12],i1[17])->(o0,o1[1x12,6nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[1]? arg[1][3] : 0;
  a1=arg[1]? arg[1][0] : 0;
  a2=arg[1]? arg[1][4] : 0;
  a3=arg[0]? arg[0][11] : 0;
  a4=arg[1]? arg[1][5] : 0;
  a5=(a3-a4);
  a5=(a2*a5);
  a1=(a1+a5);
  a5=arg[0]? arg[0][3] : 0;
  a6=(a1-a5);
  a6=(a0*a6);
  a7=arg[1]? arg[1][1] : 0;
  a3=(a3-a4);
  a3=(a0*a3);
  a7=(a7+a3);
  a3=arg[0]? arg[0][4] : 0;
  a4=(a7-a3);
  a4=(a2*a4);
  a6=(a6-a4);
  a4=arg[1]? arg[1][6] : 0;
  a8=(a6*a4);
  a9=(a8*a6);
  a1=(a1-a5);
  a1=(a2*a1);
  a7=(a7-a3);
  a7=(a0*a7);
  a1=(a1+a7);
  a7=arg[1]? arg[1][7] : 0;
  a3=(a1*a7);
  a5=(a3*a1);
  a9=(a9+a5);
  a5=arg[1]? arg[1][8] : 0;
  a10=arg[0]? arg[0][2] : 0;
  a10=(a5*a10);
  a9=(a9-a10);
  a10=arg[0]? arg[0][0] : 0;
  a11=arg[1]? arg[1][9] : 0;
  a12=(a10*a11);
  a13=(a12*a10);
  a9=(a9+a13);
  a13=arg[0]? arg[0][1] : 0;
  a14=arg[1]? arg[1][10] : 0;
  a15=(a13*a14);
  a16=(a15*a13);
  a9=(a9+a16);
  if (res[0]!=0) res[0][0]=a9;
  a11=(a11*a10);
  a12=(a12+a11);
  if (res[1]!=0) res[1][0]=a12;
  a14=(a14*a13);
  a15=(a15+a14);
  if (res[1]!=0) res[1][1]=a15;
  a5=(-a5);
  if (res[1]!=0) res[1][2]=a5;
  a7=(a7*a1);
  a3=(a3+a7);
  a7=(a2*a3);
  a4=(a4*a6);
  a8=(a8+a4);
  a4=(a0*a8);
  a6=(a7+a4);
  a6=(-a6);
  if (res[1]!=0) res[1][3]=a6;
  a8=(a2*a8);
  a3=(a0*a3);
  a6=(a8-a3);
  if (res[1]!=0) res[1][4]=a6;
  a3=(a3-a8);
  a0=(a0*a3);
  a7=(a7+a4);
  a2=(a2*a7);
  a0=(a0+a2);
  if (res[1]!=0) res[1][5]=a0;
  return 0;
}

int dynamics_solver_forcespro_objective_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

int dynamics_solver_forcespro_objective_0_alloc_mem(void) {
  return 0;
}

int dynamics_solver_forcespro_objective_0_init_mem(int mem) {
  return 0;
}

void dynamics_solver_forcespro_objective_0_free_mem(int mem) {
}

int dynamics_solver_forcespro_objective_0_checkout(void) {
  return 0;
}

void dynamics_solver_forcespro_objective_0_release(int mem) {
}

void dynamics_solver_forcespro_objective_0_incref(void) {
}

void dynamics_solver_forcespro_objective_0_decref(void) {
}

casadi_int dynamics_solver_forcespro_objective_0_n_in(void) { return 2;}

casadi_int dynamics_solver_forcespro_objective_0_n_out(void) { return 2;}

casadi_real dynamics_solver_forcespro_objective_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* dynamics_solver_forcespro_objective_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* dynamics_solver_forcespro_objective_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* dynamics_solver_forcespro_objective_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* dynamics_solver_forcespro_objective_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    default: return 0;
  }
}

int dynamics_solver_forcespro_objective_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* dynamics_solver_forcespro_inequalities_0:(i0[12],i1[17])->(o0[2],o1[2x12,5nz]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[1]? arg[1][0] : 0;
  a1=arg[1]? arg[1][4] : 0;
  a2=arg[0]? arg[0][11] : 0;
  a3=arg[1]? arg[1][5] : 0;
  a4=(a2-a3);
  a4=(a1*a4);
  a0=(a0+a4);
  a4=arg[0]? arg[0][3] : 0;
  a0=(a0-a4);
  a5=casadi_sq(a0);
  a6=arg[1]? arg[1][1] : 0;
  a7=arg[1]? arg[1][3] : 0;
  a2=(a2-a3);
  a2=(a7*a2);
  a6=(a6+a2);
  a2=arg[0]? arg[0][4] : 0;
  a6=(a6-a2);
  a3=casadi_sq(a6);
  a5=(a5+a3);
  a3=arg[1]? arg[1][11] : 0;
  a8=1.1940000000000000e+00;
  a3=(a3-a8);
  a3=casadi_sq(a3);
  a5=(a5-a3);
  if (res[0]!=0) res[0][0]=a5;
  a5=1.;
  a3=arg[1]? arg[1][14] : 0;
  a8=cos(a3);
  a9=arg[1]? arg[1][12] : 0;
  a4=(a4-a9);
  a9=(a8*a4);
  a3=sin(a3);
  a10=arg[1]? arg[1][13] : 0;
  a2=(a2-a10);
  a10=(a3*a2);
  a9=(a9+a10);
  a10=1.4142135623730951e+00;
  a11=arg[1]? arg[1][15] : 0;
  a12=2.;
  a11=(a11/a12);
  a13=2.4864999999999999e+00;
  a11=(a11+a13);
  a11=(a10*a11);
  a11=casadi_sq(a11);
  a9=(a9/a11);
  a13=(a8*a4);
  a14=(a3*a2);
  a13=(a13+a14);
  a14=(a9*a13);
  a15=(a3*a4);
  a16=(a8*a2);
  a15=(a15-a16);
  a16=arg[1]? arg[1][16] : 0;
  a16=(a16/a12);
  a12=5.9699999999999998e-01;
  a16=(a16+a12);
  a10=(a10*a16);
  a10=casadi_sq(a10);
  a15=(a15/a10);
  a4=(a3*a4);
  a2=(a8*a2);
  a4=(a4-a2);
  a2=(a15*a4);
  a14=(a14+a2);
  a14=(a14-a5);
  a14=(-a14);
  a14=exp(a14);
  a5=(a5+a14);
  a2=(1./a5);
  if (res[0]!=0) res[0][1]=a2;
  a0=(a0+a0);
  a16=(-a0);
  if (res[1]!=0) res[1][0]=a16;
  a2=(a2/a5);
  a5=(a8/a11);
  a5=(a13*a5);
  a16=(a9*a8);
  a5=(a5+a16);
  a16=(a3/a10);
  a16=(a4*a16);
  a12=(a15*a3);
  a16=(a16+a12);
  a5=(a5+a16);
  a5=(a14*a5);
  a5=(a2*a5);
  if (res[1]!=0) res[1][1]=a5;
  a6=(a6+a6);
  a5=(-a6);
  if (res[1]!=0) res[1][2]=a5;
  a11=(a3/a11);
  a13=(a13*a11);
  a9=(a9*a3);
  a13=(a13+a9);
  a10=(a8/a10);
  a4=(a4*a10);
  a15=(a15*a8);
  a4=(a4+a15);
  a13=(a13-a4);
  a14=(a14*a13);
  a2=(a2*a14);
  if (res[1]!=0) res[1][3]=a2;
  a0=(a0*a1);
  a6=(a6*a7);
  a0=(a0+a6);
  if (res[1]!=0) res[1][4]=a0;
  return 0;
}

int dynamics_solver_forcespro_inequalities_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

int dynamics_solver_forcespro_inequalities_0_alloc_mem(void) {
  return 0;
}

int dynamics_solver_forcespro_inequalities_0_init_mem(int mem) {
  return 0;
}

void dynamics_solver_forcespro_inequalities_0_free_mem(int mem) {
}

int dynamics_solver_forcespro_inequalities_0_checkout(void) {
  return 0;
}

void dynamics_solver_forcespro_inequalities_0_release(int mem) {
}

void dynamics_solver_forcespro_inequalities_0_incref(void) {
}

void dynamics_solver_forcespro_inequalities_0_decref(void) {
}

casadi_int dynamics_solver_forcespro_inequalities_0_n_in(void) { return 2;}

casadi_int dynamics_solver_forcespro_inequalities_0_n_out(void) { return 2;}

casadi_real dynamics_solver_forcespro_inequalities_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* dynamics_solver_forcespro_inequalities_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* dynamics_solver_forcespro_inequalities_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* dynamics_solver_forcespro_inequalities_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* dynamics_solver_forcespro_inequalities_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

int dynamics_solver_forcespro_inequalities_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* dynamics_solver_forcespro_cdyn_0:(i0[9],i1[3],i2[17])->(o0[9],o1[3x9,3nz],o2[9x9,20nz]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][3] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a3=(a0*a2);
  a4=arg[0]? arg[0][4] : 0;
  a5=sin(a1);
  a6=(a4*a5);
  a3=(a3-a6);
  if (res[0]!=0) res[0][0]=a3;
  a3=sin(a1);
  a6=(a0*a3);
  a7=cos(a1);
  a8=(a4*a7);
  a6=(a6+a8);
  if (res[0]!=0) res[0][1]=a6;
  a6=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a6;
  a8=3.9682539682539683e-04;
  a9=2520.;
  a10=arg[0]? arg[0][6] : 0;
  a10=(a9*a10);
  a11=8.9999999999999993e-03;
  a12=2.0000000000000000e-03;
  a12=(a12*a0);
  a13=100.;
  a12=(a12/a13);
  a11=(a11+a12);
  a12=2.9999999999999997e-04;
  a13=100000000.;
  a13=(a0/a13);
  a12=(a12*a13);
  a11=(a11+a12);
  a10=(a10-a11);
  a11=6.2168749999999995e-01;
  a12=(a11*a0);
  a13=(a12*a0);
  a10=(a10-a13);
  a13=1.5591427000000000e+04;
  a14=1.2000000000000000e+00;
  a15=10.;
  a16=arg[0]? arg[0][7] : 0;
  a17=1.4840000000000000e+00;
  a18=(a17*a6);
  a18=(a18+a4);
  a19=atan2(a18,a0);
  a19=(a16-a19);
  a19=(a15*a19);
  a20=atan(a19);
  a20=(a14*a20);
  a21=sin(a20);
  a21=(a13*a21);
  a22=sin(a16);
  a23=(a21*a22);
  a10=(a10-a23);
  a23=(a9*a4);
  a24=(a23*a6);
  a10=(a10+a24);
  a10=(a8*a10);
  if (res[0]!=0) res[0][3]=a10;
  a10=9.6999999999999997e-01;
  a24=1.6000000000000001e+00;
  a25=1.6439999999999999e+00;
  a26=(a25*a6);
  a26=(a26-a4);
  a27=atan2(a26,a0);
  a27=(a15*a27);
  a28=atan(a27);
  a28=(a24*a28);
  a29=sin(a28);
  a29=(a10*a29);
  a30=cos(a16);
  a31=(a21*a30);
  a31=(a29+a31);
  a32=(a9*a0);
  a33=(a32*a6);
  a31=(a31-a33);
  a31=(a8*a31);
  if (res[0]!=0) res[0][4]=a31;
  a31=7.3529411764705876e-05;
  a33=(a17*a21);
  a34=cos(a16);
  a35=(a33*a34);
  a29=(a25*a29);
  a35=(a35-a29);
  a35=(a31*a35);
  if (res[0]!=0) res[0][5]=a35;
  a35=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][6]=a35;
  a35=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][7]=a35;
  a35=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][8]=a35;
  a35=1.;
  if (res[1]!=0) res[1][0]=a35;
  if (res[1]!=0) res[1][1]=a35;
  if (res[1]!=0) res[1][2]=a35;
  a29=sin(a1);
  a29=(a0*a29);
  a36=cos(a1);
  a36=(a4*a36);
  a29=(a29+a36);
  a29=(-a29);
  if (res[2]!=0) res[2][0]=a29;
  if (res[2]!=0) res[2][1]=a2;
  a5=(-a5);
  if (res[2]!=0) res[2][2]=a5;
  a5=cos(a1);
  a5=(a0*a5);
  a1=sin(a1);
  a4=(a4*a1);
  a5=(a5-a4);
  if (res[2]!=0) res[2][3]=a5;
  if (res[2]!=0) res[2][4]=a3;
  if (res[2]!=0) res[2][5]=a7;
  if (res[2]!=0) res[2][6]=a35;
  a7=-2.0000003000000003e-05;
  a11=(a11*a0);
  a11=(a11+a12);
  a7=(a7-a11);
  a20=cos(a20);
  a11=casadi_sq(a18);
  a12=casadi_sq(a0);
  a11=(a11+a12);
  a18=(a18/a11);
  a18=(a15*a18);
  a19=casadi_sq(a19);
  a19=(a35+a19);
  a18=(a18/a19);
  a18=(a14*a18);
  a18=(a20*a18);
  a18=(a13*a18);
  a12=(a22*a18);
  a7=(a7-a12);
  a7=(a8*a7);
  if (res[2]!=0) res[2][7]=a7;
  a11=(a0/a11);
  a7=(a15*a11);
  a7=(a7/a19);
  a7=(a14*a7);
  a7=(a20*a7);
  a7=(a13*a7);
  a12=(a22*a7);
  a3=(a9*a6);
  a12=(a12+a3);
  a12=(a8*a12);
  if (res[2]!=0) res[2][8]=a12;
  a11=(a17*a11);
  a11=(a15*a11);
  a11=(a11/a19);
  a11=(a14*a11);
  a11=(a20*a11);
  a11=(a13*a11);
  a12=(a22*a11);
  a12=(a12+a23);
  a12=(a8*a12);
  if (res[2]!=0) res[2][9]=a12;
  if (res[2]!=0) res[2][10]=a35;
  a19=(a15/a19);
  a14=(a14*a19);
  a20=(a20*a14);
  a13=(a13*a20);
  a22=(a22*a13);
  a20=cos(a16);
  a20=(a21*a20);
  a22=(a22+a20);
  a22=(a8*a22);
  a22=(-a22);
  if (res[2]!=0) res[2][11]=a22;
  a22=(a30*a18);
  a28=cos(a28);
  a20=casadi_sq(a26);
  a14=casadi_sq(a0);
  a20=(a20+a14);
  a26=(a26/a20);
  a26=(a15*a26);
  a27=casadi_sq(a27);
  a35=(a35+a27);
  a26=(a26/a35);
  a26=(a24*a26);
  a26=(a28*a26);
  a26=(a10*a26);
  a22=(a22-a26);
  a9=(a9*a6);
  a22=(a22-a9);
  a22=(a8*a22);
  if (res[2]!=0) res[2][12]=a22;
  a0=(a0/a20);
  a20=(a15*a0);
  a20=(a20/a35);
  a20=(a24*a20);
  a20=(a28*a20);
  a20=(a10*a20);
  a22=(a30*a7);
  a22=(a20+a22);
  a22=(a8*a22);
  a22=(-a22);
  if (res[2]!=0) res[2][13]=a22;
  a0=(a25*a0);
  a15=(a15*a0);
  a15=(a15/a35);
  a24=(a24*a15);
  a28=(a28*a24);
  a10=(a10*a28);
  a28=(a30*a11);
  a28=(a10-a28);
  a28=(a28-a32);
  a28=(a8*a28);
  if (res[2]!=0) res[2][14]=a28;
  a30=(a30*a13);
  a28=sin(a16);
  a21=(a21*a28);
  a30=(a30-a21);
  a8=(a8*a30);
  if (res[2]!=0) res[2][15]=a8;
  a18=(a17*a18);
  a18=(a34*a18);
  a26=(a25*a26);
  a18=(a18+a26);
  a18=(a31*a18);
  if (res[2]!=0) res[2][16]=a18;
  a20=(a25*a20);
  a7=(a17*a7);
  a7=(a34*a7);
  a20=(a20-a7);
  a20=(a31*a20);
  if (res[2]!=0) res[2][17]=a20;
  a11=(a17*a11);
  a11=(a34*a11);
  a25=(a25*a10);
  a11=(a11+a25);
  a11=(a31*a11);
  a11=(-a11);
  if (res[2]!=0) res[2][18]=a11;
  a17=(a17*a13);
  a34=(a34*a17);
  a16=sin(a16);
  a33=(a33*a16);
  a34=(a34-a33);
  a31=(a31*a34);
  if (res[2]!=0) res[2][19]=a31;
  return 0;
}

int dynamics_solver_forcespro_cdyn_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

int dynamics_solver_forcespro_cdyn_0_alloc_mem(void) {
  return 0;
}

int dynamics_solver_forcespro_cdyn_0_init_mem(int mem) {
  return 0;
}

void dynamics_solver_forcespro_cdyn_0_free_mem(int mem) {
}

int dynamics_solver_forcespro_cdyn_0_checkout(void) {
  return 0;
}

void dynamics_solver_forcespro_cdyn_0_release(int mem) {
}

void dynamics_solver_forcespro_cdyn_0_incref(void) {
}

void dynamics_solver_forcespro_cdyn_0_decref(void) {
}

casadi_int dynamics_solver_forcespro_cdyn_0_n_in(void) { return 3;}

casadi_int dynamics_solver_forcespro_cdyn_0_n_out(void) { return 3;}

casadi_real dynamics_solver_forcespro_cdyn_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* dynamics_solver_forcespro_cdyn_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

const char* dynamics_solver_forcespro_cdyn_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

const casadi_int* dynamics_solver_forcespro_cdyn_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    case 2: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* dynamics_solver_forcespro_cdyn_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s8;
    case 2: return casadi_s9;
    default: return 0;
  }
}

int dynamics_solver_forcespro_cdyn_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* dynamics_solver_forcespro_cdyn_0rd_0:(i0[9],i1[3],i2[17])->(o0[9]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][3] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a2=(a0*a2);
  a3=arg[0]? arg[0][4] : 0;
  a4=sin(a1);
  a4=(a3*a4);
  a2=(a2-a4);
  if (res[0]!=0) res[0][0]=a2;
  a2=sin(a1);
  a2=(a0*a2);
  a1=cos(a1);
  a1=(a3*a1);
  a2=(a2+a1);
  if (res[0]!=0) res[0][1]=a2;
  a2=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a2;
  a1=3.9682539682539683e-04;
  a4=2520.;
  a5=arg[0]? arg[0][6] : 0;
  a5=(a4*a5);
  a6=8.9999999999999993e-03;
  a7=2.0000000000000000e-03;
  a7=(a7*a0);
  a8=100.;
  a7=(a7/a8);
  a6=(a6+a7);
  a7=2.9999999999999997e-04;
  a8=100000000.;
  a8=(a0/a8);
  a7=(a7*a8);
  a6=(a6+a7);
  a5=(a5-a6);
  a6=6.2168749999999995e-01;
  a6=(a6*a0);
  a6=(a6*a0);
  a5=(a5-a6);
  a6=1.5591427000000000e+04;
  a7=1.2000000000000000e+00;
  a8=10.;
  a9=arg[0]? arg[0][7] : 0;
  a10=1.4840000000000000e+00;
  a11=(a10*a2);
  a11=(a11+a3);
  a11=atan2(a11,a0);
  a11=(a9-a11);
  a11=(a8*a11);
  a11=atan(a11);
  a7=(a7*a11);
  a7=sin(a7);
  a6=(a6*a7);
  a7=sin(a9);
  a7=(a6*a7);
  a5=(a5-a7);
  a7=(a4*a3);
  a7=(a7*a2);
  a5=(a5+a7);
  a5=(a1*a5);
  if (res[0]!=0) res[0][3]=a5;
  a5=9.6999999999999997e-01;
  a7=1.6000000000000001e+00;
  a11=1.6439999999999999e+00;
  a12=(a11*a2);
  a12=(a12-a3);
  a12=atan2(a12,a0);
  a8=(a8*a12);
  a8=atan(a8);
  a7=(a7*a8);
  a7=sin(a7);
  a5=(a5*a7);
  a7=cos(a9);
  a7=(a6*a7);
  a7=(a5+a7);
  a4=(a4*a0);
  a4=(a4*a2);
  a7=(a7-a4);
  a1=(a1*a7);
  if (res[0]!=0) res[0][4]=a1;
  a1=7.3529411764705876e-05;
  a10=(a10*a6);
  a9=cos(a9);
  a10=(a10*a9);
  a11=(a11*a5);
  a10=(a10-a11);
  a1=(a1*a10);
  if (res[0]!=0) res[0][5]=a1;
  a1=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][6]=a1;
  a1=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][7]=a1;
  a1=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][8]=a1;
  return 0;
}

int dynamics_solver_forcespro_cdyn_0rd_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

int dynamics_solver_forcespro_cdyn_0rd_0_alloc_mem(void) {
  return 0;
}

int dynamics_solver_forcespro_cdyn_0rd_0_init_mem(int mem) {
  return 0;
}

void dynamics_solver_forcespro_cdyn_0rd_0_free_mem(int mem) {
}

int dynamics_solver_forcespro_cdyn_0rd_0_checkout(void) {
  return 0;
}

void dynamics_solver_forcespro_cdyn_0rd_0_release(int mem) {
}

void dynamics_solver_forcespro_cdyn_0rd_0_incref(void) {
}

void dynamics_solver_forcespro_cdyn_0rd_0_decref(void) {
}

casadi_int dynamics_solver_forcespro_cdyn_0rd_0_n_in(void) { return 3;}

casadi_int dynamics_solver_forcespro_cdyn_0rd_0_n_out(void) { return 1;}

casadi_real dynamics_solver_forcespro_cdyn_0rd_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* dynamics_solver_forcespro_cdyn_0rd_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

const char* dynamics_solver_forcespro_cdyn_0rd_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* dynamics_solver_forcespro_cdyn_0rd_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    case 2: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* dynamics_solver_forcespro_cdyn_0rd_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

int dynamics_solver_forcespro_cdyn_0rd_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* dynamics_solver_forcespro_objective_1:(i0[12],i1[17])->(o0,o1[1x12,6nz]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[1]? arg[1][3] : 0;
  a1=arg[1]? arg[1][0] : 0;
  a2=arg[1]? arg[1][4] : 0;
  a3=arg[0]? arg[0][11] : 0;
  a4=arg[1]? arg[1][5] : 0;
  a5=(a3-a4);
  a5=(a2*a5);
  a1=(a1+a5);
  a5=arg[0]? arg[0][3] : 0;
  a6=(a1-a5);
  a6=(a0*a6);
  a7=arg[1]? arg[1][1] : 0;
  a3=(a3-a4);
  a3=(a0*a3);
  a7=(a7+a3);
  a3=arg[0]? arg[0][4] : 0;
  a4=(a7-a3);
  a4=(a2*a4);
  a6=(a6-a4);
  a4=arg[1]? arg[1][6] : 0;
  a8=(a6*a4);
  a9=(a8*a6);
  a1=(a1-a5);
  a1=(a2*a1);
  a7=(a7-a3);
  a7=(a0*a7);
  a1=(a1+a7);
  a7=arg[1]? arg[1][7] : 0;
  a3=(a1*a7);
  a5=(a3*a1);
  a9=(a9+a5);
  a5=arg[1]? arg[1][8] : 0;
  a10=arg[0]? arg[0][2] : 0;
  a10=(a5*a10);
  a9=(a9-a10);
  a10=arg[0]? arg[0][0] : 0;
  a11=arg[1]? arg[1][9] : 0;
  a12=(a10*a11);
  a13=(a12*a10);
  a9=(a9+a13);
  a13=arg[0]? arg[0][1] : 0;
  a14=arg[1]? arg[1][10] : 0;
  a15=(a13*a14);
  a16=(a15*a13);
  a9=(a9+a16);
  if (res[0]!=0) res[0][0]=a9;
  a11=(a11*a10);
  a12=(a12+a11);
  if (res[1]!=0) res[1][0]=a12;
  a14=(a14*a13);
  a15=(a15+a14);
  if (res[1]!=0) res[1][1]=a15;
  a5=(-a5);
  if (res[1]!=0) res[1][2]=a5;
  a7=(a7*a1);
  a3=(a3+a7);
  a7=(a2*a3);
  a4=(a4*a6);
  a8=(a8+a4);
  a4=(a0*a8);
  a6=(a7+a4);
  a6=(-a6);
  if (res[1]!=0) res[1][3]=a6;
  a8=(a2*a8);
  a3=(a0*a3);
  a6=(a8-a3);
  if (res[1]!=0) res[1][4]=a6;
  a3=(a3-a8);
  a0=(a0*a3);
  a7=(a7+a4);
  a2=(a2*a7);
  a0=(a0+a2);
  if (res[1]!=0) res[1][5]=a0;
  return 0;
}

int dynamics_solver_forcespro_objective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

int dynamics_solver_forcespro_objective_1_alloc_mem(void) {
  return 0;
}

int dynamics_solver_forcespro_objective_1_init_mem(int mem) {
  return 0;
}

void dynamics_solver_forcespro_objective_1_free_mem(int mem) {
}

int dynamics_solver_forcespro_objective_1_checkout(void) {
  return 0;
}

void dynamics_solver_forcespro_objective_1_release(int mem) {
}

void dynamics_solver_forcespro_objective_1_incref(void) {
}

void dynamics_solver_forcespro_objective_1_decref(void) {
}

casadi_int dynamics_solver_forcespro_objective_1_n_in(void) { return 2;}

casadi_int dynamics_solver_forcespro_objective_1_n_out(void) { return 2;}

casadi_real dynamics_solver_forcespro_objective_1_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* dynamics_solver_forcespro_objective_1_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* dynamics_solver_forcespro_objective_1_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* dynamics_solver_forcespro_objective_1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* dynamics_solver_forcespro_objective_1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    default: return 0;
  }
}

int dynamics_solver_forcespro_objective_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* dynamics_solver_forcespro_inequalities_1:(i0[12],i1[17])->(o0[2],o1[2x12,5nz]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[1]? arg[1][0] : 0;
  a1=arg[1]? arg[1][4] : 0;
  a2=arg[0]? arg[0][11] : 0;
  a3=arg[1]? arg[1][5] : 0;
  a4=(a2-a3);
  a4=(a1*a4);
  a0=(a0+a4);
  a4=arg[0]? arg[0][3] : 0;
  a0=(a0-a4);
  a5=casadi_sq(a0);
  a6=arg[1]? arg[1][1] : 0;
  a7=arg[1]? arg[1][3] : 0;
  a2=(a2-a3);
  a2=(a7*a2);
  a6=(a6+a2);
  a2=arg[0]? arg[0][4] : 0;
  a6=(a6-a2);
  a3=casadi_sq(a6);
  a5=(a5+a3);
  a3=arg[1]? arg[1][11] : 0;
  a8=1.1940000000000000e+00;
  a3=(a3-a8);
  a3=casadi_sq(a3);
  a5=(a5-a3);
  if (res[0]!=0) res[0][0]=a5;
  a5=1.;
  a3=arg[1]? arg[1][14] : 0;
  a8=cos(a3);
  a9=arg[1]? arg[1][12] : 0;
  a4=(a4-a9);
  a9=(a8*a4);
  a3=sin(a3);
  a10=arg[1]? arg[1][13] : 0;
  a2=(a2-a10);
  a10=(a3*a2);
  a9=(a9+a10);
  a10=1.4142135623730951e+00;
  a11=arg[1]? arg[1][15] : 0;
  a12=2.;
  a11=(a11/a12);
  a13=2.4864999999999999e+00;
  a11=(a11+a13);
  a11=(a10*a11);
  a11=casadi_sq(a11);
  a9=(a9/a11);
  a13=(a8*a4);
  a14=(a3*a2);
  a13=(a13+a14);
  a14=(a9*a13);
  a15=(a3*a4);
  a16=(a8*a2);
  a15=(a15-a16);
  a16=arg[1]? arg[1][16] : 0;
  a16=(a16/a12);
  a12=5.9699999999999998e-01;
  a16=(a16+a12);
  a10=(a10*a16);
  a10=casadi_sq(a10);
  a15=(a15/a10);
  a4=(a3*a4);
  a2=(a8*a2);
  a4=(a4-a2);
  a2=(a15*a4);
  a14=(a14+a2);
  a14=(a14-a5);
  a14=(-a14);
  a14=exp(a14);
  a5=(a5+a14);
  a2=(1./a5);
  if (res[0]!=0) res[0][1]=a2;
  a0=(a0+a0);
  a16=(-a0);
  if (res[1]!=0) res[1][0]=a16;
  a2=(a2/a5);
  a5=(a8/a11);
  a5=(a13*a5);
  a16=(a9*a8);
  a5=(a5+a16);
  a16=(a3/a10);
  a16=(a4*a16);
  a12=(a15*a3);
  a16=(a16+a12);
  a5=(a5+a16);
  a5=(a14*a5);
  a5=(a2*a5);
  if (res[1]!=0) res[1][1]=a5;
  a6=(a6+a6);
  a5=(-a6);
  if (res[1]!=0) res[1][2]=a5;
  a11=(a3/a11);
  a13=(a13*a11);
  a9=(a9*a3);
  a13=(a13+a9);
  a10=(a8/a10);
  a4=(a4*a10);
  a15=(a15*a8);
  a4=(a4+a15);
  a13=(a13-a4);
  a14=(a14*a13);
  a2=(a2*a14);
  if (res[1]!=0) res[1][3]=a2;
  a0=(a0*a1);
  a6=(a6*a7);
  a0=(a0+a6);
  if (res[1]!=0) res[1][4]=a0;
  return 0;
}

int dynamics_solver_forcespro_inequalities_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f5(arg, res, iw, w, mem);
}

int dynamics_solver_forcespro_inequalities_1_alloc_mem(void) {
  return 0;
}

int dynamics_solver_forcespro_inequalities_1_init_mem(int mem) {
  return 0;
}

void dynamics_solver_forcespro_inequalities_1_free_mem(int mem) {
}

int dynamics_solver_forcespro_inequalities_1_checkout(void) {
  return 0;
}

void dynamics_solver_forcespro_inequalities_1_release(int mem) {
}

void dynamics_solver_forcespro_inequalities_1_incref(void) {
}

void dynamics_solver_forcespro_inequalities_1_decref(void) {
}

casadi_int dynamics_solver_forcespro_inequalities_1_n_in(void) { return 2;}

casadi_int dynamics_solver_forcespro_inequalities_1_n_out(void) { return 2;}

casadi_real dynamics_solver_forcespro_inequalities_1_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* dynamics_solver_forcespro_inequalities_1_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* dynamics_solver_forcespro_inequalities_1_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* dynamics_solver_forcespro_inequalities_1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* dynamics_solver_forcespro_inequalities_1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

int dynamics_solver_forcespro_inequalities_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
