# RL Training Configuration for MPCC Expert Learning
# This file contains only the parameters that are actually used in the code

# Environment Configuration
environment:
  evaluation_episodes: 10     # Number of episodes for evaluation
  normalize_observations: false # Whether to normalize observations
  normalize_rewards: true     # Whether to normalize rewards

# PPO Hyperparameters
ppo:
  # Core PPO parameters
  learning_rate: 1.0e-3       # Learning rate for policy and value networks
  n_steps: 2048               # Number of steps to collect per environment
  batch_size: 64              # Mini-batch size for optimization
  n_epochs: 10                # Number of optimization epochs per iteration
  gamma: 0.99                 # Discount factor
  gae_lambda: 0.95            # GAE lambda parameter
  clip_range: 0.2             # PPO clipping range
  
  # Regularization
  ent_coef: 0.005             # Entropy coefficient (higher = more exploration)
  vf_coef: 0.5                # Value function coefficient
  max_grad_norm: 0.5          # Maximum gradient norm for clipping
  
  # Policy network architecture
  policy_net_arch:
    # Policy network layers
    pi: [64, 128, 256, 256, 128, 64]
    # Value network layers  
    vf: [64, 128, 256, 256, 128, 64]
  
  activation_function: "ReLU"  # Activation function (ReLU, Tanh)

# Training Configuration
training:
  total_timesteps: 1000000          # Total training steps (1M)
  parallel_environments: 16          # Number of parallel training environments
  eval_frequency: 10000             # Steps between evaluations
  save_frequency: 50000             # Steps between model saves
  
  # Device settings
  device: "cuda"                    # Device: "auto", "cpu", "cuda"

# Logging and Monitoring
logging:
  tensorboard_log: "./logs/tensorboard/"
  experiment_name: "mpcc_expert_learning"

# Model Saving
model_saving:
  save_path: "./logs/models/"

# DRL_PNC_self Environment 
RL_PNC_self:
  parameters:
    # Vehicle parameters (consistent with vehicleparams.yaml)
    L: 0.063          # lf + lr = 0.03 + 0.033
    width: 0.02       # Small scale model width
    v_max: 3.0        # From mpccparams vx_max
    v_min: 0.05       # From mpccparams vx_min  
    theta_max: 0.40   # From mpccparams delta_max
    theta_rate_max: 2.0 # From mpccparams deltadot_max
    acc_max: 10.0     # From mpccparams ddot_max
    acc_min: 10.0     # From mpccparams ddot_min (abs)
    dT: 0.03          # Small timestep for small scale
    
    # Path parameters
    straight_path: false
    global_visual: true
    
    # Sensor parameters (scaled down)
    sensor_range: 2.0   # Scaled for small model
    car_arround: 4
    
    # Obstacle parameters
    N_OBST: 0
    vob_max: 1.5        # Scaled obstacle speed
  
  # Initial conditions (from simulationparams.yaml)
  initial:
    current_x: 0.0
    current_y: 0.0
    current_yaw: 0.0
    vx0: 1.0           # From simulationparams vx0